name: slang
version: 0.1.0
homepage: https://github.com/gyarab/2023-4e-suchy-slang#readme
license: MIT
license-file: LICENSE
author: Adam Suchý

dependencies:
  - base >= 4.7 && < 5
  - array
  - containers
  - megaparsec

executable:
  source-dirs: src
  main: Main.main
  build-tools:
    - alex:alex
  generated-other-modules: Lexer
